version: "3"
services:

  ecustos-ms-search-php:
    image: srvcloudbuild/ecustos-ms-search_app:${VERSION}
    build:
      context: ./
      dockerfile: ./build/docker/Dockerfile
    container_name: ecustos-ms-search-php
    restart: unless-stopped
    volumes:
      - .:/var/www:cached
    networks:
      - ecustos-ms-search_net

  ecustos-ms-search-db:
    image: mysql:8.0.17
    container_name: ecustos-ms-search-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - "ecustos-ms-search_data:/var/lib/mysql:cached"
    ports:
      - "${DB_PORT}:3306"
    networks:
      - ecustos-ms-search_net

  ecustos-ms-search-nginx:
    image: nginx:alpine
    container_name: ecustos-ms-search-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - .:/var/www:cached
      - ./build/nginx:/etc/nginx/conf.d/:cached
    networks:
      - ecustos-ms-search_net

  ecustos-ms-search-elastic:
      env_file: .env
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
      volumes:
        - ./build/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ecustos-ms-search_data:/usr/share/elasticsearch/data
        # - type: bind
        #   source: ./elasticsearch/config/elasticsearch.yml
        #   target: /usr/share/elasticsearch/config/elasticsearch.yml
        #   read_only: true
        # - type: volume
        #   source: elasticsearch
        #   target: /usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        ELASTIC_PASSWORD: changeme
        discovery.type: single-node
        transport.host: 127.0.0.1
        cluster.name: elk-cluster
      networks:
        - ecustos-ms-search_net

    # image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    # ports:
    #   - "9200:9200"
    #   - "9300:9300"
    # configs:
    #   - source: elastic_config
    #     target: /usr/share/elasticsearch/config/elasticsearch.yml
    # environment:
    #   ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    #   ELASTIC_PASSWORD: changeme
    #   # Use single node discovery in order to disable production mode and avoid bootstrap checks.
    #   # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
    #   discovery.type: single-node
    #   # Force publishing on the 'elk' overlay.
    #   network.publish_host: _eth0_
    # networks:
    #   - elk
    # deploy:
    #   mode: replicated
    #   replicas: 1

volumes:
  ecustos-ms-search_data:

networks:
  ecustos-ms-search_net:
